const CONSTANTS = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  REGIS_START: 'REGIS_START',
  REGIS_FAILED: 'REGIS_FAILED',
  REGIS_SUCCESS: 'REGIS_SUCCESS',
  LOGOUT: 'LOGOUT',
  ME_START: 'ME_START',
  ME_SUCCESS: 'ME_SUCCESS',
  ME_FAILED: 'ME_FAILED',

  LINK_GENERATE_START: 'LINK_GENERATE_START',
  LINK_GENERATE_SUCCESS: 'LINK_GENERATE_SUCCESS',
  LINK_GENERATE_FAILED: 'LINK_GENERATE_FAILED',
  LINK_GET_ALL_START: 'LINK_GET_ALL_START',
  LINK_GET_ALL_SUCCESS: 'LINK_GET_ALL_SUCCESS',
  LINK_GET_ALL_FAILED: 'LINK_GET_ALL_FAILED',
  LINK_GET_ONE_START: 'LINK_GET_ONE_START',
  LINK_GET_ONE_SUCCESS: 'LINK_GET_ONE_SUCCESS',
  LINK_GET_ONE_FAILED: 'LINK_GET_ONE_FAILED',
}

export default CONSTANTS
